### ISSUE TITLE
Test suite not compatible with ES6

### ISSUE THREAD

**Issue by dj-sf** [learn-co-curriculum/using-active-model-serializer-lab#10]
After debugging some issues, I realized that this and some other labs in this section have difficulties with the new ES6 syntax of JavaScript.  Most notably, the tests do not recognize variables declared with "let"... they only recognize those declared with "var".  This should be either corrected or a note should be made in the lab readme not to use "let".  The same should be done with other labs with the same testing setup as this one.

**Comment by kyleblee** [comment]
Yep... took me a solid 30–45 minutes of hair pulling before seeing this Issue and figuring out that my `for...of` statement was causing the test to fail, even though it was working perfectly in the browser. Nice.

**Comment by tuzmusic** [comment]
I haven't gotten to your `for...of` issue yet, but I am also having the problem of specs failing even though they work in the browser. The specs I'm having trouble with are the ones that click a button or link, to expand the product description or to go to the next product. These functions work in the browser. I tried changing my `var`s to `let`s, to no avail.
