### ISSUE TITLE
deprecated dependancy issues

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/using-active-model-serializer-lab#18]
20:57:41] (master) using-active-model-serializer
-lab-v-000
// ♥gem install bundler
Successfully installed bundler-2.0.1
Parsing documentation for bundler-2.0.1
Done installing documentation for bundler after 5
 seconds
1 gem installed
[20:58:07] (master) using-active-model-serializer
-lab-v-000
// ♥bundle install
Fetching gem metadata from https://rubygems.org/.

............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Bundler could not find compatible versions for
gem "bundler":
  In Gemfile:
rails (~> 4.2) was resolved to 4.2.11.1,
which depends on
      bundler (>= 1.3.0, < 2.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of
Bundler.
Perhaps you need to update Bundler by running
`gem install bundler`?

**Comment by maxwellbenton** [comment]
Hi @atxrenegade,

Thank you providing this feedback. We've identified that this lab did not properly update for online students in a recent Ruby/Rails upgrade. It has now received the updated content and this issue should no longer occur.
