### ISSUE TITLE
active model serializer gem issues

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/using-active-model-serializer-lab#8]
It looks like there are some issues with the Active Model Serializer gem. They were being tracked here: https://github.com/learn-co-students/using-active-model-serializer-lab-v-000/issues/42#issuecomment-303126322

Note: learn-co-curriculum and learn-co-students are in sync, so it's not a deploy issue. Looks like this lab needs a once over to update it for the new version of the gem.

@Lukeghenco @jmburges @gj

**Comment by cernanb** [comment]
@aturkewi Looks like the specs were updated to account for the latest version of the gem. I think the issue that was open in learn-co-students (#42) leads some students to install v 0.9.0 of the ams gem - even though it was updated to work with 0.10.0. Now that you closed that issue hopefully shouldn't happen again.

**Comment by aturkewi** [comment]
Nice! So it looks like this was fixed with PR #9 ?
